#!/data/data/com.termux/files/usr/bin/bash

# Inspired by Khansaad1275 made by funnut
# https://github.com/funnut/yt-pobieracz

# Kliknij w Udostępnij za pomocą Termux lub uruchom: bash ~/bin/termux-url-opener "www.linkdowideo.pl"

cat << "EOF"
                _
   ___ ___   __| | ___
  / __/ _ \ / _` |/ _ \
 | (_| (_) | (_| |  __/
(_)___\___/ \__,_|\___| yt-pobieracz
EOF

mkdir -p "/data/data/com.termux/files/home/storage/downloads/yt-pobieracz"
fpath="/data/data/com.termux/files/home/storage/downloads/yt-pobieracz/%(title)s.%(ext)s"

if [[ -z "$1" ]]; then
    echo "Użycie: termux-url-opener <URL>"
    exit 1
fi

if [[ "$1" == *"shorts"* ]]; then
  yt-dlp -o "$fpath" "$1"
  exit
else
	echo " "
fi

echo -e "   1. Music Mp3♫"
echo -e "   2. Wideo 360p"
echo -e "   3. Wideo 480p"
echo -e "   4. Wideo 720p"
echo -e "   5. Wideo 1080p"
echo -e "   6. Wideo 2160p"
echo -e "   7. Anuluj"
echo
printf "Wybierz format: "
read choice
echo

case $choice in
	1)
	yt-dlp -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o "$fpath" "$1"

    ;;
	2)
	yt-dlp -f "bestvideo[height<=360]+bestaudio/best[height<=360]" -o "$fpath" "$1"
	;;

	3)
	yt-dlp -f "bestvideo[height<=480]+bestaudio/best[height<=480]" -o "$fpath" "$1"
	;;

	4)
	yt-dlp -f "bestvideo[height<=720]+bestaudio/best[height<=720]" -o "$fpath" "$1"
	;;

	5)
	yt-dlp -f "bestvideo[height<=1080]+bestaudio/best[height<=1080]" -o "$fpath" "$1"
	;;

	6)
	yt-dlp -f "bestvideo[height<=2160]+bestaudio/best[height<=2160]" -o "$fpath" "$1"
	;;

	7)
	exit
	;;

	*)
	yt-dlp -f "bestvideo[height<=2160]+bestaudio/best[height<=2160]" -o "$fpath" "$1"
esac

echo
read -p "Naciśnij Enter, aby zakończyć..."
