#!/usr/bin/bash

# Zainspirowany przez Khansaad1275 stworzony przez funnut
# https://github.com/funnut/yt-pobieracz
# Jeżeli podoba Ci się projekt, zostaw gwiazdkę na GitHubie

# Udostępnij wideo lub muzykę poprzez aplikacje Termux, po uruchomieniu skryptu wybierz format.
# Możesz też uruchomić ten sam skrypt podając odnośnik do wideo ręcznie: bash ~/bin/termux-url-opener "www.linkdowideo.pl”

# Kod dostępny na zasadach licencji MIT (zobacz plik LICENSE).

cat << "EOF"
                _
   ___ ___   __| | ___
  / __/ _ \ / _` |/ _ \
 | (_| (_) | (_| |  __/
(_)___\___/ \__,_|\___| yt-pobieracz
EOF

path="/data/data/com.termux/files/home/storage/downloads/yt-pobieracz"
mkdir -p "$path"
fpath="$path/%(title)s.%(ext)s"

if [[ -z "$1" ]]; then
    echo "Użycie: termux-url-opener <URL>"
    exit 1
fi

if [[ "$1" == *"shorts"* ]]; then
  yt-dlp --merge-output-format mp4 -o "$path/[shorts] %(title)s.%(ext)s" "$1"
  exit
else
	echo " "
fi

echo -e "   1. Music Mp3♫"
echo -e "   2. Wideo 360p"
echo -e "   3. Wideo 480p"
echo -e "   4. Wideo 720p"
echo -e "   5. Wideo 1080p"
echo -e "   6. Wideo 2160p"
echo -e "   7. Anuluj"
echo
printf "Wybierz format: "
read choice
echo

case $choice in
	1)
	yt-dlp -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o "$fpath" "$1"

    ;;
	2)
	yt-dlp -f "bestvideo[height<=360]+bestaudio/best[height<=360]" --merge-output-format mp4 -o "$fpath" "$1"
	;;

	3)
	yt-dlp -f "bestvideo[height<=480]+bestaudio/best[height<=480]" --merge-output-format mp4 -o "$fpath" "$1"
	;;

	4)
	yt-dlp -f "bestvideo[height<=720]+bestaudio/best[height<=720]" --merge-output-format mp4 -o "$fpath" "$1"
	;;

	5)
	yt-dlp -f "bestvideo[height<=1080]+bestaudio/best[height<=1080]" --merge-output-format mp4 -o "$fpath" "$1"
	;;

	6)
	yt-dlp -f "bestvideo[height<=2160]+bestaudio/best[height<=2160]" --merge-output-format mp4 -o "$fpath" "$1"
	;;

	7)
	exit
	;;

	*)
	yt-dlp -f "bestvideo[height<=2160]+bestaudio/best[height<=2160]" --merge-output-format mp4 -o "$fpath" "$1"
esac

echo
read -p "Naciśnij Enter, aby zakończyć..."


#   _
# _|_  ._ ._   _|_
#  ||_|| || ||_||_
#       www.github.com/funnut
