#!/data/data/com.termux/files/usr/bin/bash
#
# Zainspirowany przez Khansaad1275 stworzony przez funnut
# https://github.com/funnut/yt-pobieracz
# Jeżeli podoba Ci się projekt, zostaw gwiazdkę na GitHubie!
# Kod dostępny na zasadach licencji MIT (zobacz plik LICENSE).
#
#   _
# _|_  ._ ._   _|_
#  ||_|| || ||_||_
#       www.github.com/funnut

show_usage () {
  echo "Użycie: $(basename $0) <URL>"
  echo "Nakładka programu yt-dlp do wygodnego pobierania multimediów z sieci."
}

cat << "EOF"
                _
   ___ ___   __| | ___
  / __/ _ \ / _` |/ _ \
 | (_| (_) | (_| |  __/
(_)___\___/ \__,_|\___| yt-pobieracz

EOF

while true; do
    FPATH="/data/data/com.termux/files/home/storage/downloads/yt-pobieracz/%(title)s.%(ext)s"
    LOGFILE="/data/data/com.termux/files/home/bin/yt.log"

    [[ $# -lt 1 || $# -gt 1 ]] && show_usage && exit 1

    case "$1" in
      "help" )
      show_usage
      exit ;;
      *"playlist"* )
      FPATH="/data/data/com.termux/files/home/storage/downloads/yt-pobieracz/playlist/%(title)s.%(ext)s" ;;
      *"shorts"* )
      yt-dlp --merge-output-format mp4 -o "/data/data/com.termux/files/home/storage/downloads/yt-pobieracz/[shorts] %(title)s.%(ext)s" "$1"
      exit
    esac

    echo "   1. Music Mp3♫"
    echo "   2. Wideo 360p"
    echo "   3. Wideo 480p"
    echo "   4. Wideo 720p"
    echo "   5. Wideo 1080p"
    echo "   6. Wideo 2160p"
    echo "   7. Anuluj"
    echo
    read -p "Wybierz format: " choice
    echo

    echo "$(date '+%m-%d %H:%M') [$choice] "$1"" >> $LOGFILE

    case $choice in
      1) yt-dlp -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0 -o "$FPATH" "$1" ;;
      2) yt-dlp -f "bestvideo[height<=360]+bestaudio/best[height<=360]" -o "$FPATH" "$1" ;;
      3) yt-dlp -f "bestvideo[height<=480]+bestaudio/best[height<=480]" -o "$FPATH" "$1" ;;
      4) yt-dlp -f "bestvideo[height<=720]+bestaudio/best[height<=720]" -o "$FPATH" "$1" ;;
      5) yt-dlp -f "bestvideo[height<=1080]+bestaudio/best[height<=1080]" -o "$FPATH" "$1" ;;
      6) yt-dlp -f "bestvideo[height<=2160]+bestaudio/best[height<=2160]" -o "$FPATH" "$1" ;;
      7) exit ;;
      *) yt-dlp -f "bestvideo[height<=2160]+bestaudio/best[height<=2160]" -o "$FPATH" "$1"
    esac

    echo
    read -p "Enter, aby zakończyć r aby powtórzyć... " reply
    [[ ! "$reply" == [Rr] ]] && exit
    echo
done
